# Generated by Django 4.2.2 on 2023-06-11 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndustryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Industry Category',
                'verbose_name_plural': 'Industry Categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.ManyToManyField(to='account.emissionpackage')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_limit', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('subscription_package', models.ManyToManyField(to='account.subscriptionpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500, null=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(max_length=500, null=True)),
                ('industry_category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.industrycategory')),
                ('root_admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(auto_now=True)),
                ('add_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('company_profie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.profile')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subscriptionplan')),
            ],
        ),
    ]
