# Generated by Django 4.2.2 on 2023-06-11 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=500, null=True)),
                ('formula', models.CharField(blank=True, max_length=500, null=True)),
                ('molecular_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('heating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('GWP', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlareInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emission_factor', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('activity', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('flare_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True)),
                ('compound', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flare_emission.compound')),
            ],
        ),
    ]
